# Generated by Django 6.0.5 on 2026-05-26 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='localizacao',
            field=models.CharField(default='laboratorio Principal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.CharField(default='Disponivel', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manutencao',
            name='data',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
    ]
